### ISSUE TITLE
Math.random() randomizing filename to be opened within init context causes uploads to get corrupted

### ISSUE THREAD

**Issue by vderelle** [grafana/k6#2266] opened 2021-11-29 08:28 UTC
Hi,

I've come across a bug/unexpected behavior whereby using Math.random() to randomly open() a file inside the init/global context causes the HTTP PUT requests to interrupt each other when multiple VUs land on the same random file. This behavior does not occur if not using Math.random(), i.e. having multiple VUs upload the same file, which is what you would expect. It's baffling as to why the introduction of Math.random() would cause this.

Fails:
```
const filename = Math.floor((Math.random() * 10) + 1)
const imageFile = open(`pic/png/${filename.png}`, "b")
```

Works:
```
const filename = 6;
const imageFile = open(`pic/png/${filename.png}`, "b")
```

Works:
```
const imageFile = open(`pic/png/${__VU}.png`, "b");
```
^ currently using this last approach to have some variability, although not true randomness, across the various VUs in terms of the file that they upload. 

The HTTP PUT operation within the load test script uploads to S3. It consistently fails with corrupted file uploads if Math.random() lands on the same number and thus pics the same file to open across multiple VUs.

The web service we are load testing accepts pictures with different characteristics from our users. To have a more accurate representation of behavior under load it's better to add some entropy and randomize which PNGs get uploaded.

Thank you for your help.

**Comment by MStoykov** [comment] 2021-11-29 12:31
Hi @vderelle, can you elaborate on what "requests to interrupt each other when multiple VUs land on the same random file."  even better if you can make a small script that reproduces what you are seeing using https://httpbin.test.k6.io/ 

Also, can you try to open all the files on `__VU == 0` and see if this isn't a duplicate of #1771 ? Which I think is the only thing possible that we know off

**Comment by vderelle** [comment] 2021-12-02 07:31
Hi @MStoykov 

The files uploaded through the PUT request bellow do not finish to completion. In other words, the transfers seem to get interrupted before completion and are therefore corrupted when downloading subsequently from S3.

```
const baseUploadUrl = 'https://<some.url.corresponding.to.s3>/';
const baseWssUrl = 'wss://<some.url.corresponding.websocket.server.managed.by.aws>/dev?uuid=';

const filename = Math.floor((Math.random() * 10) + 1) 
const imageFile = open(`faces/samples/png/${filename}.png`, "b"); 

export default function () {

	let randomUUID = uuidv4(); 
	let uploadImageUrl = baseUploadUrl + randomUUID + "." + "png"; 

	let wssConnectUrl = baseWssUrl + randomUUID;

	const resWss = ws.connect(wssConnectUrl, function (socket) {
		socket.on('open', () => {
			console.log(`VU ${__VU} websocket connected`)
			const headers = {
				'Content-Type': 'image/png', // PNG
				'x-amz-acl': 'bucket-owner-full-control'
			};

			var resHttp = http.put(uploadImageUrl, imageFile, { headers: headers });
			
			console.log(`VU ${__VU} uploaded image ${__VU}.png`);
			
			check(resHttp, {'image upload is status 200': (r) => r.status === 200});
		});
		
		socket.on('message', (msg) => {	
			let jmsg = JSON.parse(msg);
			check(jmsg, {
				'websocket message received. image processing complete': (r) => r['completion'] == "success"
			});
			socket.close();
		});
		
		socket.on('disconnect', () => {
			console.log(`VU ${__VU} websocket disconnected`);
		});

		socket.on('error', function (e) {
      		if (e.error() != 'websocket: close sent') {
        		console.log(`VU ${__VU} An unexpected error occured: `, e.error());
      		}
    	});
	});
}
```

**Comment by MStoykov** [comment] 2021-12-02 08:07
@vderelle if this is the #1771 you can check by printing the `length` of each file in the default with it's name and checking if they match - if they don't then it's that issue. 

Given what you are saying this seems to be the case, and the current workaround is to open all of them in `__VU == 0` - you don't need to save them, just open them once there. Sorry for the inconvience

I will be closing this as it's a duplicate of #1771 if you think it isn't - please comment here so we can reopen it.

**Closed by MStoykov** 2021-12-02 08:07 UTC
Labels: evaluation needed, awaiting user
