### ISSUE TITLE
Disable warning / error logs with command line

### ISSUE THREAD

**Issue by 320IM** [grafana/k6#2681] opened 2022-09-13 05:04 UTC
### Feature Description

While doing the soak test , got too much below error, consumed huge space to save logs
level=warning msg="Request Failed" error="Post \"**** connect: cannot assign requested address"

### Suggested Solution (optional)

have a flag that user can disable popup it.

**Comment by na--** [comment] 2022-09-13 16:26
Thanks for opening this issue! It is a bit of a duplicate of https://github.com/grafana/k6/issues/1681, but it's more targeted and something that should probably be considered for the new HTTP API we have planned (https://github.com/grafana/k6/issues/2461), so I'll leave it open. I also opened an issue for the [httpx library](https://k6.io/docs/javascript-api/jslib/httpx/) on [jslib.k6.io](https://jslib.k6.io), to potentially explore some simpler JS solutions in the meantime.

Until we have any of that, you can write your own wrapper that catches exceptions when `throw` is `true` and just ignores them, or one of the other workarounds mention in https://github.com/grafana/k6/issues/1681#issuecomment-787978692.

**Comment by 320IM** [comment] 2022-09-14 03:32
Thank you ,both two work around works

**Comment by imiric** [comment] 2023-03-28 14:35
Given that there are acceptable workarounds for this, I'll close the issue.

As a sidenote, I don't see this as being part of the HTTP API, but as something that should be addressed globally in #1681. After all, the HTTP API will only log events, and it's not concerned with how those events are shown to the user.

**Closed by imiric** 2023-03-28 14:35 UTC
Labels: enhancement, ux, new-http
