### ISSUE TITLE
Missing MQTT Support

### ISSUE THREAD

**Issue by manan-at-norgic** [grafana/k6#3280] opened 2023-08-16 06:56 UTC
### Feature Description

There is web socket support in k6.js but there is missing MQTT support if someone need to test mqtt server he/she need to write a complete web socket wrapper on top of k6 web socket.

### Suggested Solution (optional)

By imlimenting [emitter-io mqtt client](https://github.com/emitter-io/emitter) which is also written in go and it have extensive scope to support different languages like javascript, java, c#/.net, Go, c/c++, python, node etc

**Comment by olegbespalov** [comment] 2023-08-16 15:38
Hi @manan-at-norgic !

It seems to me like a duplicate of the https://github.com/grafana/k6/issues/1269, I'd recommend upvoting it and continuing the discussion there.

The is also a xk6's extension https://github.com/grafana/k6/issues/1269#issuecomment-778166511 exists which implements the MQTT. I'd recommend trying it, maybe it sorts your needs.

For now, closing this issue.

**Closed by olegbespalov** 2023-08-16 15:38 UTC
Labels: feature
