### ISSUE TITLE
Permission denied when running k6 new using docker

### ISSUE THREAD

**Issue by iskyd** [grafana/k6#3643] opened 2024-03-15 14:05 UTC
### Brief summary

After pulling the image running k6 new using docker will result in "permission denied"
Adding --user root seems to solve the problem.

### k6 version

k6 v0.49.0 (commit/b5328aa782, go1.21.6, linux/amd64)

### OS

Linux ubuntu

### Docker version and image (if applicable)

24.0.7, build afdd53b

### Steps to reproduce the problem

```
docker pull grafana/k6
docker run --rm -i -v $PWD:/app -w /app grafana/k6 new
```

### Expected behaviour

I expect script.js will be generated

### Actual behaviour

Get the following error msg 
time="2024-03-15T14:02:24Z" level=error msg="open script.js: permission denied"

**Comment by oleiade** [comment] 2024-03-18 10:59
Hi @iskyd 👋🏻 

I'm unable to reproduce the issue on MacOS, and unfortunately don't have a Linux VM at hand to try and reproduce the issue. Could you @codebien and @mstoykov (I know you're under fedora, but it might still worth giving it a go?) please give it a try, and let us know if you're able to reproduce the issue? 🙇🏻

**Comment by mstoykov** [comment] 2024-03-22 10:38
Have your tried adding `--user $UID` - this worked for another user [here](https://community.grafana.com/t/permission-denied-on-k6-docker-json-output/99466/2?u=mstoykov)

**Comment by iskyd** [comment] 2024-03-22 13:25
`--user $UID` seems to work

**Comment by codebien** [comment] 2024-03-22 14:27
@oleiade we need to report back in the doc this info. Can you please open an issue there? /cc @heitortsergent

**Comment by oleiade** [comment] 2024-03-26 16:19
I have created the document issue [#1536](https://github.com/grafana/k6-docs/issues/1536) in the documentation repository accordingly, with the high prio label.

We should move any further discussion there, and I will therefore close this issue 👍🏻

**Closed by oleiade** 2024-03-26 16:19 UTC
Labels: bug
