### ISSUE TITLE
k6 doesn't work with custom DNS servers (Arch/Manjaro)

### ISSUE THREAD

**Issue by koynoyno** [grafana/k6#2118] opened 2021-08-22 22:42 UTC
Trying to launch test example from docs, getting an error.

## Environment
- k6 version: k6 v0.32.0 (2021-05-12T15:30:26+0000/5e42319, go1.16.3, linux/amd64)
- OS and version: Linux 5.10.56-1-MANJARO x86_64 21.1.0 Pahvo

## Expected Behavior
Tests run

## Actual Behavior
```
  scenarios: (100.00%) 1 scenario, 1 max VUs, 10m30s max duration (incl. graceful stop):
           * default: 1 iterations for each of 1 VUs (maxDuration: 10m0s, gracefulStop: 30s)

WARN[0000] Request Failed                                error="Get \"https://test.k6.io\": lookup test.k6.io on [::1]:53: dial udp [::1]:53: socket: address family not supported by protocol"

running (00m01.0s), 0/1 VUs, 1 complete and 0 interrupted iterations
default ✓ [================================] 1 VUs  00m01.0s/10m0s  1/1 iters, 1 per VU

     data_received..............: 0 B     0 B/s
     data_sent..................: 0 B     0 B/s
     http_req_blocked...........: avg=0s min=0s med=0s max=0s p(90)=0s p(95)=0s
     http_req_connecting........: avg=0s min=0s med=0s max=0s p(90)=0s p(95)=0s
     http_req_duration..........: avg=0s min=0s med=0s max=0s p(90)=0s p(95)=0s
     http_req_failed............: 100.00% ✓ 1   ✗ 0  
     http_req_receiving.........: avg=0s min=0s med=0s max=0s p(90)=0s p(95)=0s
     http_req_sending...........: avg=0s min=0s med=0s max=0s p(90)=0s p(95)=0s
     http_req_tls_handshaking...: avg=0s min=0s med=0s max=0s p(90)=0s p(95)=0s
     http_req_waiting...........: avg=0s min=0s med=0s max=0s p(90)=0s p(95)=0s
     http_reqs..................: 1       0.989937/s
     iteration_duration.........: avg=1s min=1s med=1s max=1s p(90)=1s p(95)=1s
     iterations.................: 1       0.989937/s
     vus........................: 1       min=1 max=1
     vus_max....................: 1       min=1 max=1
```

## Steps to Reproduce the Problem
1. Download k6 (`yay k6`)
2. Run test example from README (with `http.get('https://test.k6.io');` line)

**Comment by koynoyno** [comment] 2021-08-22 22:59
I had `GRUB_CMDLINE_LINUX="ipv6.disable=1"` option turned on in `/etc/default/grub` (I set it manually a while ago to fix unstable Wi-Fi, some weird but working solution from the internet.

After commenting out this line I get other error:

```
WARN[0000] Request Failed                                error="Get \"https://test.k6.io\": lookup test.k6.io on [::1]:53: read udp [::1]:59383->[::1]:53: read: connection refused"
```

Launching k6 as `k6 run script.js --dns policy=onlyIPv4` shows the same error.

**Comment by koynoyno** [comment] 2021-08-22 23:32
[This](https://caddy.community/t/cant-get-a-certificate-acme-fails-oddly/6660/3) one post helped a little bit.

Turns out I had an empty `/etc/resolv.conf`. Sequence of commands

```
sudo rm /etc/resolv.conf
sudo ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
sudo resolvconf -u
```

repopulated the file. Now, when I run `k6 run script.js`, the doesn't fail instantly but it still fails:

```
  scenarios: (100.00%) 1 scenario, 1 max VUs, 10m30s max duration (incl. graceful stop):
           * default: 1 iterations for each of 1 VUs (maxDuration: 10m0s, gracefulStop: 30s)

WARN[0020] Request Failed                                error="Get \"https://test.k6.io\": lookup test.k6.io on 1.0.0.1:53: read udp 10.10.5.25:60039->1.0.0.1:53: i/o timeout"

running (00m21.0s), 0/1 VUs, 1 complete and 0 interrupted iterations
default ✓ [===========================] 1 VUs  00m21.0s/10m0s  1/1 iters, 1 per VU

     data_received..............: 0 B     0 B/s
     data_sent..................: 0 B     0 B/s
     http_req_blocked...........: avg=0s  min=0s  med=0s  max=0s  p(90)=0s  p(95)=0s 
     http_req_connecting........: avg=0s  min=0s  med=0s  max=0s  p(90)=0s  p(95)=0s 
     http_req_duration..........: avg=0s  min=0s  med=0s  max=0s  p(90)=0s  p(95)=0s 
     http_req_failed............: 100.00% ✓ 1   ✗ 0  
     http_req_receiving.........: avg=0s  min=0s  med=0s  max=0s  p(90)=0s  p(95)=0s 
     http_req_sending...........: avg=0s  min=0s  med=0s  max=0s  p(90)=0s  p(95)=0s 
     http_req_tls_handshaking...: avg=0s  min=0s  med=0s  max=0s  p(90)=0s  p(95)=0s 
     http_req_waiting...........: avg=0s  min=0s  med=0s  max=0s  p(90)=0s  p(95)=0s 
     http_reqs..................: 1       0.047604/s
     iteration_duration.........: avg=21s min=21s med=21s max=21s p(90)=21s p(95)=21s
     iterations.................: 1       0.047604/s
     vus........................: 1       min=1 max=1
     vus_max....................: 1       min=1 max=1
```

**Comment by koynoyno** [comment] 2021-08-22 23:35
Ok, I solved this problem. I had quite a configuration, my `/etc/resolv.conf` was getting parameters from `/etc/resolvconf.conf` because I manually set up 1.1.1.1 DNS server. I commented out everything in the latter file, run 

```
sudo rm /etc/resolv.conf
sudo ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
sudo resolvconf -u
```

sequence again, and now k6 works.

This is nuts. Why it doesn't work with manual DNS settings? I have no desire to use the default DNS settings my provider sends me.

I consider this a bug.

**Comment by MStoykov** [comment] 2021-08-23 07:12
Hi @koynoyno, glad you managed to fix it.

Can you please post all the relevant parts of your configuration so we can reproduce this?

**Comment by koynoyno** [comment] 2021-08-23 07:18
@MStoykov 

`/etc/resolvconf.conf`
```
name_servers="1.1.1.1 1.0.0.1"
```

This way you should be able to reproduce the bug.

**Comment by imiric** [comment] 2021-09-06 11:00
Hi @koynoyno,

I wasn't able to reproduce this issue on a latest Manjaro installation following your instructions, and running `k6 run 'github.com/grafana/k6/samples/thresholds_readme_example.js'` worked fine with k6 v0.32.0.

The latest error you're getting (`lookup test.k6.io on 1.0.0.1:53: read udp 10.10.5.25:60039->1.0.0.1:53: i/o timeout`) is a generic network timeout error indicating that k6 wasn't able to resolve using `1.0.0.1:53`, so this seems out of scope to be a k6 issue. k6 itself doesn't do DNS resolution internally and leverages Go's stdlib resolvers, but this is unlikely to be a Go issue either.

My guess is that you have some firewall or network setting that is blocking attempts to use Cloudflare's resolvers. You should be able to confirm this with `dig @1.0.0.1 test.k6.io` or `nc -vzuw1 1.0.0.1 53`.

**Comment by na--** [comment] 2023-03-07 06:36
Closing this, since there hasn't been any activity here for quite a long time... If someone stumbles on this and has a similar problem, please open a new issue that references this one.

**Closed by na--** 2023-03-07 06:36 UTC
Labels: bug, awaiting user
