### ISSUE TITLE
Large (30-40MB) data chunks loaded through imports are copied over each VU

### ISSUE THREAD

**Issue by Dasha27** [grafana/k6#3515] opened 2023-12-20 13:41 UTC
### Brief summary

k6 consumes a lot of memory when using imports. Any non-empty import affects the test which causes a problem with running stability tests.

### k6 version

k6 v0.46.0, go1.21.0

### OS

Debian 11

### Steps to reproduce the problem

We use several scripts with imports like this:

```
import http from 'k6/http';
import exec from 'k6/execution'
import {check, fail, sleep, group} from 'k6';
import {sha512} from 'k6/crypto';
import {getSession} from '../start_session.js';
import {headers, env, testType, testConfig, trendStats, testTags} from "../constants.js"
import {name, config} from "../configuration.js"
import {generatePayload1, generatePayload2, generatePayload3, generatePayload4} from "../payload.js";
import {function1, function2, function3} from "../functions.js";
```
The test with such imports consumes all the memory of the load generator (16 GB) within 1 hour of a fix-load test with 5000 VUs.

Here in file you can see the memory consumption for 500 VUs
[k6_mem_deduplicated.log](https://github.com/grafana/k6/files/13727925/k6_mem_deduplicated.log)

### Expected behaviour

The test should run without any memory leaks even on the high load and using different imports.

### Actual behaviour

The test consumes all the memory within a quite short period. It happens even without using any xk6 extensions and writing any logs/artifacts. Using only one file without any imports (except k6 libraries) works fine and without memory leaks.

**Comment by joanlopez** [comment] 2023-12-20 14:14
Hi @Dasha27,

Thanks for details. I'll try to reproduce it. But meanwhile, would you be able to to share a minimal reproducible example?
I see a lot of custom files (e.g. `start_session.js`, `constants.js`, `configuration.js`, `payload.js`, etc), and I guess whatever that's there could make the difference.

Thanks!

**Comment by Dasha27** [comment] 2023-12-20 14:47
Hi @joanlopez,

Sure, here are some examples of the custom files.
[start_session.txt](https://github.com/grafana/k6/files/13728674/start_session.txt)
[constants.txt](https://github.com/grafana/k6/files/13728675/constants.txt)
[functions.txt](https://github.com/grafana/k6/files/13728676/functions.txt)
[payload.txt](https://github.com/grafana/k6/files/13728677/payload.txt)
[configuration.txt](https://github.com/grafana/k6/files/13728678/configuration.txt)

**Comment by joanlopez** [comment] 2023-12-20 15:03
Sorry @Dasha27, but I still cannot see what the main (default) test function actually does in your case, so although I appreciate you shared the helper files imported (what you pointed as what seems to be reason of huge memory consumption), I'd need to at least have a clue of how the test looks like, to understand how those 5000VUs will behave, and what could be causing the memory consumption (ideally try to reproduce it and profile).

So, please could you shed some light? Thanks!

**Comment by Dasha27** [comment] 2023-12-20 15:16
Sure, sorry for misunderstanding, here is the main file
[main.txt](https://github.com/grafana/k6/files/13728997/main.txt)

**Comment by joanlopez** [comment] 2023-12-27 14:27
Hi @Dasha27,

I've spent some time trying to reproduce the same behavior (distinct memory consumption with/out imports) with no luck. So, at this point, I'd like to give you two suggestions. Either:

- Try to extract some memory profiles from your high memory consumption executions (see [here](https://grafana.com/docs/k6/latest/using-k6/k6-options/reference/#profiling-enabled) how to enable profiling endpoints in k6), so we can identify what pieces are consuming more memory and try to reason why.
- Try to strip out some of your test bits, so you will either:
  - Identify what specific piece is causing the high memory consumption.
  - End up having a much simpler test that you can share with us, so it's easier for us to reproduce your casuistic.

Honestly, I've spent some time trying to reproduce it with the bits you shared so far, but I had no luck, and honestly I struggled a bit . However, I have to admit that after a quick look, I haven't detected yet any red flag that might be causing such a high memory consumption as you mention. 

<br/>

Also, note that high memory consumption for certain large and long tests might be expected. You can look for some references along [these benchmarks](https://github.com/grafana/k6-benchmarks/tree/master/results/v0.42.0), which are a bit outdated, but shouldn't differ much. Additionally, if you're curious about related conversations, you can take a look at the discussion we recently had at https://github.com/grafana/k6/issues/3498, and what's described in https://github.com/grafana/k6/issues/2367 (which is still tbd, btw).

Thanks!

**Comment by joanlopez** [comment] 2024-07-22 14:45
Hi @metaturso,

From k6 docs, you can read:

> In general, all external modules added to a test project have a negative impact on performance, as they further increase the memory footprint and CPU usage.
>
> Usually, this is not a big problem as each application only allocates these resources once. In k6, however, every VU has a separate JavaScript virtual machine (VM), duplicating the resource usage once each.

So, looking at the example you provided, I think **that huge memory usage is _just_ expected,** as these ~35MB would be copied over each VU (_cause each VU is an isolated JS runtime, and the `data` variable needs to be set on each of them_). 

In fact, I just profiled the memory usage of such example, and the consumption is around ~14GB, which matches with the rough math: 400 VUs x 35MB. The memory usage from the OS standpoint (process) is much higher (around ~50GB), but that's probably because Go's garbage collector isn't very optimal for such use scenario.

That said, **what I'd recommend you to avoid such large memory consumption is:**
- Use [`SharedArray`](https://grafana.com/docs/k6/latest/javascript-api/k6-data/sharedarray/), designed precisely to handle such scenarios.
- Make `data` be a function that returns the data, or use a data file (CSV, JSON, etc) and open it with [`k6/experimental/fs.open`](https://grafana.com/docs/k6/latest/javascript-api/k6-experimental/fs/open/).

For instance, note the difference in your script from:

```js
// script.js
import { data } from "large-csv-file-now-converted-to-javascript.js";

export function setup() {
    ...
}

export const options = {
   ...
};

export function leak() {
    // empty body.
}

// large-csv-file-now-converted-to-javascript.js
export const data = [
    {
        path: "/",
        query: "",
        method: "GET",
    },
    { /* ... */ },
    { /* ... */ },
      /* ... */
    { /* ... */ },
    { /* ... */ },
];
```

vs

```js
// script.js
import { getData } from "large-csv-file-now-converted-to-javascript.js";
import { SharedArray } from 'k6/data';

const data = new SharedArray('data', function () {
  return getData();
});

export function setup() {
    ...
}

export const options = {
   ...
};

export function leak() {
    // empty body.
}

// large-csv-file-now-converted-to-javascript.js
export function getData() return [
        {
            path: "/",
            query: "",
            method: "GET",
        },
        { /* ... */ },
        { /* ... */ },
          /* ... */
        { /* ... */ },
        { /* ... */ },
    ];
}
```

Please, note that only modifying your example to use `SharedArray` isn't enough, as what you want is also avoiding the memory allocation of `data` for each VU, which would remain if you `import { data } from file`, directly as raw data.

I hope that helps! @Dasha27 could you confirm that would also help in your case (which I guess is a more complex scenario of what @metaturso shared)? If so, I'd suggest to close the issue, as I'd mark what's described as _expected behavior_ and just consider what I suggested above as solution.

Thanks! 🙇🏻

**Comment by joanlopez** [comment] 2024-10-07 08:43
Considering that there has been no news since more than two months ago, and that the exploration was quite successful: the root cause is clearly identified, as well as the possible workaround; I'm about to close this issue, as I guess the only remaining work from this discussion is already stated in other issues, like #3237.

If you have any other trouble, feel free to open another issue. Thanks! 🙇🏻

**Closed by joanlopez** 2024-10-07 08:43 UTC
Labels: performance, triage
