### ISSUE TITLE
Parsing error when output have leading zero

### ISSUE THREAD

**Issue by 403-html** [grafana/k6#3758] opened 2024-05-27 19:08 UTC
### Brief summary

A parsing error occurs when numerical outputs with leading zeros are misinterpreted as octal values instead of decimal, leading to error throws and skipping iterations.

### k6 version

k6 v0.50.0 (go1.22.1, darwin/arm64)

### OS

MacOS Sonoma 14.4.1 (23E224)

### Steps to reproduce the problem

A parsing error occurs when responses contains leading zeros in their responses. This issue arises when using `response.json()`. It does interpret such numbers as octal (base-8) rather than decimal (base-10), leading to errors and skipped iteration (for example response may randomly deliver **expected** response with leading zero). I created reproductable demo here ([repository](https://github.com/403-html/k6-parsing-error)). Otherwise we can't go easily into content of body.

### Expected behaviour

Parser in example `k6 run tests/k6-script-plain.js` should properly get value of response's body as "01" and finalize check on it

### Actual behaviour

Parser in example `k6 run tests/k6-script-plain.js` throws an error  

```
ERRO\[0000\] GoError: cannot parse json due to an error at line 1, character 2 , error: invalid character '1' after top-level value  
       at reflect.methodValueCall (native)  
       at file:///Users/tymoteusz.stepien/Documents/k6-parsing-error/tests/k6-script-plain.js:20:8(23)  executor=shared-iterations scenario=default source=stacktrace  
```

when it comes to the parsing text response of "01"

**Comment by mstoykov** [comment] 2024-05-27 21:16
Hi, thanks for the really nice repo to reproduce this :tada: :bow:. 

When the error happens it is because the whole response is `01` not `"01"` or something like that. 

In that case as per the [JSON specification](https://www.json.org/json-en.html) this is not a correct value. You can scroll down to the diagram for `number`. 

You will notice that if there is a leading `0` it actually awaits either a `.` which will make it a float or and `e`/`E` for an exponent. Either way it is not about base-8 and it isn't parsing the string `"01"`. 

The same is the behaviour if you provide this value to `JSON.parse` in a browser or node.   

As such I am closing this as this works exactly as expected.

**Closed by mstoykov** 2024-05-27 21:16 UTC
Labels: bug, triage
