### ISSUE TITLE
The document is not clear for calling https

### ISSUE THREAD

**Issue by manojgct84** [grafana/k6#2642] opened 2022-08-09 10:16 UTC
### Feature Description

I am trying to make HTTPS calls, when I use JMeter, I don't pass any cert. 

When using K6, I am trying to use 
```
export let options = { 
    maxRedirects: 4,tlsAuth: [{cert: CERT,key: KEY,},],
};
```

But I am getting **_WARN[0006] Request Failed                                error="Post \"https://gcp.manoj.service.com": x509: “*.lab-us-gcp.manoj.service.com” certificate is not standards compliant"_**

**Comment by na--** [comment] 2022-08-09 10:25
What is your OS and the k6 version you are using? Because when searching for "certificate is not standards compliant", I stumble on a bunch of Go MacOS issues like https://github.com/golang/go/issues/51991 :thinking:  

Also, please use the correct issue template when submitting an issue.

**Comment by manojgct84** [comment] 2022-08-09 11:24
I am using macOS and K6 - 0.39.0 V.

**Comment by na--** [comment] 2022-08-09 12:15
I don't completely understand what's going on here, but from the issue I linked above, it seems like a Go problem specifically on MacOS, so I am not sure what we can do about it, if anything... :confused:  If anyone knows or has MacOS and can reproduce this, please lend a hand.

**Comment by codebien** [comment] 2023-08-15 07:35
Closing as the issue doesn't sound to be directly generated by k6. Feel free to reopen if you have more details.

**Closed by codebien** 2023-08-15 07:35 UTC
Labels: bug, help wanted, evaluation needed, awaiting user
