### ISSUE TITLE
Adding Proxy/CONNECT headers?

### ISSUE THREAD

**Issue by SalmaanP** [grafana/k6#1140] opened 2019-09-04 02:12 UTC
I see requests through proxy can be made by setting environment variables `HTTP_PROXY` & `HTTPS_PROXY`. This seems to work fine, but is there a way to add CONNECT headers? I can already see user-agent header is added, any way to add custom headers? curl provides an option `--proxy-header` for this.

example request would be
```
CONNECT www.example.com:443 HTTP/1.1
Host: www.example.com:443
User-Agent: Go-http-client/1.1
CustomHeader: blah
```

**Comment by na--** [comment] 2019-09-04 07:20
No, unfortunately `CONNECT` requests / different proxies per request are currently not supported. https://github.com/loadimpact/k6/issues/1045 is the issue that currently tracks that, though we will probably create a separate overarching issue about custom transports (https://github.com/loadimpact/k6/issues/1045#issuecomment-501150436) that would sum up all of the use cases for them.

**Comment by SalmaanP** [comment] 2019-09-08 20:42
Makes sense. I've created a small [PR](https://github.com/loadimpact/k6/pull/1147) specifically for adding proxy headers, let me know if it can be merged standalone without the other features you mentioned.

**Comment by mstoykov** [comment] 2023-12-11 10:16
Closing as this is a duplicate of #1045

**Closed by mstoykov** 2023-12-11 10:16 UTC
Labels: duplicate, enhancement, feature, new-http
