### ISSUE TITLE
Provide an API to exit a test

### ISSUE THREAD

**Issue by ppcano** [grafana/k6#1001] opened 2019-04-17 15:52 UTC
The [k6 API ](https://docs.k6.io/docs) does not provide an API to exit a load test.  The [fail](https://docs.k6.io/docs/fail-err) does not cover this case.

A common workaround is to configure a [threshold that aborts the test](https://docs.k6.io/docs/thresholds#section-aborting-a-test-when-a-threshold-is-crossed) when the threshold is crossed.

```js
import { sleep } from "k6";
import http from "k6/http";
import { Counter } from "k6/metrics";

export let options = {
    stages: [
        { duration: "30s", target: 50 }
    ],
    thresholds: {
        "myThresholdMetric": [{threshold: "count<1", abortOnFail: true}]
    }
};

const myThresholdMetric = new Counter("myThresholdMetric");

export default function() {
    http.get("https://test.loadimpact.com/");
    if (__VU === 1 && __ITER === 1) { 
        myThresholdMetric.add(1);
    }
    sleep(3);
};
```

But this or other workarounds have a few inconveniences or limitations:

1. The [Threshold](https://docs.k6.io/docs/thresholds) API works well for evaluating complex conditions but the API is not intuitive or simple when you want just to check a simple condition. 

```js
    if (condition) { 
        exit();
    }
```
2. It cannot `exit` the load test on a non-error mode. 

```js
exit(0);
```

3. It cannot provide different `exit` codes. Related issue: [Different exit codes for different errors](https://github.com/loadimpact/k6/issues/870)

```js
exit(5);
```

4. it cannot provide user message

```js
exit(10, “service was not available”);
```

5. The API should also work on the `setup/teardown` methods.

```js
export function teardown(time) {
    if (condition) { 
        exit(1);
    }
}
```

The `exit` API is a suggestion, but in any case, I think it could be a good addition if k6 provides an API to support these cases during local and cloud execution.  Some users have already asked for a similar utility.

**Comment by na--** [comment] 2019-04-18 05:21
This is a partial duplicate of an [older issue](https://github.com/loadimpact/k6/issues/939), but I'll close the old one and leave this one open, since this is more detailed and somewhat easier to find. Just a couple of comments on the proposed API:
- I prefer `abort()` as the name of the new function, as proposed in the other issue. It's makes it more clear that we're aborting the whole test. `exit()` also has connotations of immediate termination, while k6 actually has to perform some housekeeping when it aborts tests, like sending latest metrics to collectors, etc.
- This likely shouldn't be a global function, rather it would probably be better if users have to import it as `import { abort, sleep } from "k6";`

**Comment by RobinHoutevelts** [comment] 2020-10-22 16:46
Since we now have the powerful scenario's. Would it be possible to abort a scenario so the next one starts?

That would be a massive win for me.

**Comment by na--** [comment] 2021-03-18 16:19
We discussed this a bit internally, and this is the specification we arrived at:

- The function name should be `abortTest()` and it will be in the root `k6` module (i.e. it would be accessible from test scripts via `import { abortTest } from 'k6';`.
- Once called, `abortTest()` would stop the whole test run and the k6 process will exit with a custom fixed non-zero exit code `107`.
- In contrast to the old way of stopping the test run (a threshold on a custom metric with `abortOnFail: true`) mentioned above, `abortTest()` should make sure that the VU that called it stops immediately after, i.e. no more instructions from its current iteration are executed and no more iterations are started. 
- The `teardown()` function should still be executed after the test run aborts in this way.
- The run status of the test run will be [`aborted by script`](https://github.com/loadimpact/k6/blob/9d973f564f5a8e3754fa51be4b22a03295cbae9e/lib/collector.go#L47) (e.g. for when `k6 run --out cloud` is used)

So, a JS script that uses it should look somewhat like this:

```js
import http from 'k6/http';
import { abortTest, sleep } from 'k6';

export default function () {
    // ... some test logic ...
    if (Math.random() < 0.01) { // or some actual test abort check
        console.log('mayday, mayday');
        abort();
        console.log('this should never be executed');
    }
    // ...
}
```

**Comment by basickarl** [comment] 2021-05-24 15:46
> Since we now have the powerful scenario's. Would it be possible to abort a scenario so the next one starts?
> 
> That would be a massive win for me.

I agree with this, this would be a total win here also! Something like `abortScenario`. My scenario needs to end once all users have received a specific HTTP response from the API we are testing.

**Comment by na--** [comment] 2021-05-25 07:39
@basickarl, aborting a single scenario would be a lot more complicated in the distributed/cloud execution mode, so it's out of scope for this issue. If you want, feel free to create a new issue with details of your specific use case.

**Closed** 2021-12-17 13:40 UTC
Labels: ux, feature, evaluation needed
