### ISSUE TITLE
Request Params sent as array 

### ISSUE THREAD

**Issue by anwesh-b** [grafana/k6#2794] opened 2022-12-04 15:56 UTC
### Brief summary

I am sending a post request with params, header in it

```js
import http from "k6/http";

export default function () {
  const url2 = "myURL";

  const payload2 = <MyPayload>;

  const params = {
    headers: {
      "Content-Type": "application/json",
      authorization: <MyToken >,
    },
  };

  const res = http.post(url2, JSON.stringify(payload2), params);

  console.log({ res });
}
```

The request is sent with params modified.
The header of request becomes:
```
      "Content-Type": ["application/json"],
      authorization: [<MyToken >],
```
As this is now array, the server did not expect array to be there and sends authorization error

Are there any walkaround to bypass this issue?

### k6 version

0.41.0

### OS

Fedora 36

### Steps to reproduce the problem

Send request with params using http provieded by k6

### Expected behaviour

I expected my headers to be sent as defined in params

### Actual behaviour

Params are modified as array

**Comment by na--** [comment] 2022-12-05 07:52
I think this is a duplicate of https://github.com/grafana/k6/issues/2559

That is, k6 is not sending the headers as an array. However, when you try to inspect what headers were actually sent in the request by reading them from the `request.headers[header]` property of the `Response` object, those values are reported as an array by k6, due to the Go stdlib reasons discussed in the other issue. To verify that, please make a request to a service like https://httpbin.org/anything and see what it reports as the `headers` it received.

**Closed** 2023-03-07 06:38 UTC
Labels: bug, duplicate, evaluation needed, awaiting user
