### ISSUE TITLE
TEST: Need to test the Issue CI

### ISSUE THREAD

**Issue by javaducky** [grafana/k6#3168] opened 2023-07-05 15:30 UTC
### Brief summary

Just needing a non-core developer to create a simple issue for testing the CI.

### k6 version

v0.45.0

### OS

Mac

### Steps to reproduce the problem

Blah, blah, blah, then blah.

### Expected behaviour

k6 should then blah.

### Actual behaviour

Exptected to blah, but instead it blahed.

**Comment by olegbespalov** [comment] 2023-07-05 18:48
Hey, @javaducky !

Sorry, can't reproduce :crying_cat_face: 

I've tried a simple script
```
export default () => {
   console.log("blah");
}
```

and it didn't blahed

![image](https://github.com/grafana/k6/assets/5425600/a4a416db-a7eb-4cd3-a03e-4f68127ec690)

Closing the issue for now

**Closed by olegbespalov** 2023-07-05 18:48 UTC
Labels: bug
