### ISSUE TITLE
Aggregation + group by on tagged custom counters don't seem to work properly

### ISSUE THREAD

**Issue by trueneu** [grafana/k6#4100] opened 2024-12-11 20:56 UTC
### Brief summary

The group by tags feature from Grafana Cloud doesn't seem to work if custom K6 counters are tagged (when using K6 as a datasource).

I'm not sure if the problem is on K6 side or Grafana Cloud side.

### k6 version

0.55 with patch from https://github.com/grafana/k6/issues/4050

### OS

Ubuntu 22.04

### Steps to reproduce the problem

 - Take this sample test:

```
import {Counter} from "k6/metrics";

const c = new Counter('test_counter');

export default () => {
    c.add(1, {mytag: "1"});
    c.add(1, {mytag: "2"});
};
```

 - Run it for 10 iterations
 - In Grafana Cloud, Explore the k6 datasource for the test metrics; metric is test_counter, aggregation is cumulative sum, with group by mytag

If I do not understand how the aggregation or grouping works, I apologize.

### Expected behaviour

Both test_counter{mytag="1"} and test_counter{mytag="2"} have 10 as a value of cumulative sum. test_counter without grouping has 20 as a value.

### Actual behaviour

Both test_counter{mytag="1"} and test_counter{mytag="2"} have 20 as a value of cumulative sum.

<img width="805" alt="Image" src="https://github.com/user-attachments/assets/fa71dd12-f1d8-4543-a037-4fe7e755ac2c" />

If no grouping is applied, the value is still 20:

<img width="806" alt="Image" src="https://github.com/user-attachments/assets/bef2d575-ecf7-4fa9-8876-1820dcc0e6db" />

This can be worked around with a tag filter, but this kinda defeats the idea of grouping:

<img width="809" alt="Image" src="https://github.com/user-attachments/assets/2ce71e8d-a932-45d2-acf7-982f3c219aa4" />

**Comment by mstoykov** [comment] 2024-12-12 15:41
Hi @trueneu, thanks for reporting this.

I tried to get this and while I did think I got it, it turned out that I had `stacked lines` on and that basically meants one of the dots was at 10 and the other at 20 (stacked on top of it). But the values were always 10, just the graph.

For the record I literally ran your script with `k6 cloud -i 10 script.js` and with `k6 run -o cloud -i 10 script.js` and both test worked as expected.


Given that I can't reproduce it and this seems to be a GCk6 thing - please contact support and they will be able to look at the exact test run you did.

I will close this for now, if it turns out it is a problem within k6 cli, please comment agani and we will reopen it.

**Closed by mstoykov** 2024-12-12 15:41 UTC
Labels: bug, triage

**Comment by trueneu** [comment] 2024-12-12 17:26
Thank you @mstoykov
