### ISSUE TITLE
Forward thresholds execution results when running `k6 -o cloud scripts.js`

### ISSUE THREAD

**Issue by oleiade** [grafana/k6#2626] opened 2022-08-01 09:24 UTC
### Feature Description

As of this writing, when k6 is run with its output set to the cloud (`k6 run -o cloud script.js`), it observes the same behavior as when `k6 run` is executed, and does not forward its thresholds results to the cloud backend. It results in thresholds results not being displayed in k6 cloud's web interface because their result were simply not sent.

In an ideal state, we would prefer for `k6 run -o cloud` to evaluate thresholds locally as it is the case currently, but we would also like it to include the results of the thresholds' execution in the output and forward it to the cloud to be able to interpret and display them. 

### Suggested Solution (optional)

It is yet unclear how we would address this, and will probably involve some non OSS work behind closed doors. 

### Already existing or connected issues / PRs (optional)

- Part of the initial scope of [#1443](https://github.com/grafana/k6/issues/1443) was to actually define a shared representation format for thresholds, with the long-term idea to first unify execution, and then allow k6 to stream thresholds results to the cloud?

**Comment by na--** [comment] 2022-08-01 10:14
Hmm is this a regression? IIRC this used to work with old k6 versions, and the code still seems to be in the cloud output :confused: See:
https://github.com/grafana/k6/blob/1e8468292ab5eb0d2333b1278b44e81c5cbef679/output/cloud/output.go#L296
https://github.com/grafana/k6/blob/1e8468292ab5eb0d2333b1278b44e81c5cbef679/output/cloud/output.go#L682-L702

**Comment by na--** [comment] 2022-08-01 10:58
Ah, so the actual task is about the metric values that are compared to the threshold constraints, since we only send the threshold names and their pass/fail status at the moment: https://github.com/grafana/k6/blob/1e8468292ab5eb0d2333b1278b44e81c5cbef679/cloudapi/api.go#L40

But then this is a duplicate of this older issue, so I'll close it: https://github.com/grafana/k6/issues/1956

**Closed by na--** 2022-08-01 10:58 UTC
Labels: cloud, feature, evaluation needed
