### ISSUE TITLE
K6 supporting grpc for streaming use cases

### ISSUE THREAD

**Issue by rahul2july** [grafana/k6#2383] opened 2022-02-09 10:14 UTC
### Feature Description

Hi,
I am looking to use k6 for grpc load testing.
Everything looks good k6 but got this through the documentations:
"""we're happy to introduce a native client for gRPC communication. In this early release, we've settled for providing a solid experience for unary calls. If any of the other modes would be particularily useful for you, we'd love to hear about your use case so we can move it up our backlog."""

"""k6 is a great tool for writing performance tests in Javascript. It supports gRPC unary calls by default. But for now, streaming is not supported at all. And it is not easy to add this functionality easily to the current implementation"""

Please could you share the timelines when streaming would be officially supported?

**Comment by na--** [comment] 2022-02-09 10:33
Thanks for opening this issue, though I will have to close it, since it's a duplicate of https://github.com/grafana/k6/issues/2383.

To answer the question, streaming support depends on having event loops in VUs (https://github.com/grafana/k6/issues/882). The good news is that we have an open PR to add that event loop support (https://github.com/grafana/k6/pull/2228) and hope to merge and release it in the next k6 version (v0.37.0), slated to be released around March 14th. Optimistically, gRPC streaming might arrive soon after that, probably first as an [xk6](https://github.com/grafana/xk6) extension (e.g. along the lines of https://github.com/grafana/k6/issues/2315), and later in the k6 core. 

However, we haven't prioritized anything after v0.37.0, so I can't promise anything yet. If someone is willing to contribute a high-quality implementation (first as an extension), it will probably speed things up significantly. If not, at least give a :+1: to https://github.com/grafana/k6/issues/2383, so we can gauge user demand for the feature more accurately in our prioritization discussions.

**Closed by na--** 2022-02-09 10:33 UTC
Labels: duplicate, feature

**Comment by rahul2july** [comment] 2022-02-17 05:02
Hi,
If we need to make this change , could you suggest where all we need to make the relevant changes.
We will give a shot and raise a pull request if this works.

**Comment by na--** [comment] 2022-02-17 10:38
The gRPC code is located here: https://github.com/grafana/k6/tree/master/js/modules/k6/grpc
Though again, I suggest waiting for https://github.com/grafana/k6/pull/2228 to be merged (or developing on top of its branch) and probably also waiting for https://github.com/grafana/k6/issues/2315 (since we plan to work on that very soon).

Please don't comment in the closed issue anymore and instead use https://github.com/grafana/k6/issues/2020 for discussing your proposed solution, if you start working on this.
