### ISSUE TITLE
__ENV  variables defined in scenario are not available in setup or teardown hooks 

### ISSUE THREAD

**Issue by patrick-janeiro** [grafana/k6#2342] opened 2022-01-18 00:53 UTC
### Brief summary

After having written a custom extension I was hoping to initialize the extension with certain parameters to influence the behaviour of the extension. The original solution was for the extension to read this parameters from os environment variables, however we thought a more elegant solution would be to initialize the extension in the `setup` hook.

This would make it so we can tune all our params for the test within the options for the scenario. This would make the test configuration self contained which was nice. However, after testing this approach I noticed that `__ENV` was missing my variable at setup. 

Is this the intended behaviour? I

### k6 version

v0.34.1

### OS

MacOs 11

### Steps to reproduce the problem

the following is my test.js file:

```
import { runTest } from "./test-core.js";

export const options = {
    scenarios: {
        example_scenario: {
            executor: 'per-vu-iterations',
            gracefulStop: '5s',
            env: { FOO: 'BAR' },

            maxDuration: '10s',
        }
    }
};

console.log("Running init... ");
console.log(JSON.stringify(`Env variable value: ${__ENV.FOO}`));

export function setup() {
    console.log("Setting Up Test")
    console.log(JSON.stringify(`Env variable value: ${__ENV.FOO}`));
}



export default function () {
    console.log("Running VU")
    console.log(JSON.stringify(`Env variable value: ${__ENV.FOO}`));
    runTest()
}

export function teardown(data) {
    console.log("Tearing Down Test")
    console.log(JSON.stringify(`Env variable value: ${__ENV.FOO}`));
}
```

### Expected behaviour

```

INFO[0005] Setting Up Test                               source=console
INFO[0005] "Env variable value: BAR"               source=console
```

### Actual behaviour

The test file above produces the following: 

```
INFO[0005] Running init...                               source=console
INFO[0005] "Env variable value: undefined"               source=console
INFO[0005] Running init...                               source=console
INFO[0005] "Env variable value: undefined"               source=console
INFO[0005] Setting Up Test                               source=console
INFO[0005] "Env variable value: undefined"               source=console
INFO[0005] Running VU                                    source=console
INFO[0005] "Env variable value: BAR"                     source=console
INFO[0005] Running init...                               source=console
INFO[0005] "Env variable value: undefined"               source=console
INFO[0005] Tearing Down Test                             source=console
INFO[0005] "Env variable value: undefined"               source=console
```

**Comment by na--** [comment] 2022-01-18 09:02
The `env` option in every scenario config changes `__ENV` only for iterations of that scenario. To specify global environment variables across all scenarios and `setup()` and `teardown()`, you can use the `--env` CLI flag or just specify normal OS environment variables (assuming `--include-system-env-vars` is enabled, which it is by default for `k6 run`). For more details, see https://k6.io/docs/using-k6/options/#supply-environment-variables and https://k6.io/docs/using-k6/environment-variables/

I'll close this issue, since it is the intended behavior and not a bug. Please comment here or open a new one with more details about your use case, if the global environment variables are not sufficient for it.

**Closed by na--** 2022-01-18 09:02 UTC
Labels: question
