### ISSUE TITLE
Align values in the end-of-test summary output

### ISSUE THREAD

**Issue by mpandurovic** [grafana/k6#1024] opened 2019-05-17 12:24 UTC
It would be nice to have values such as `avg`,   `max`,  `med`, `min` etc. aligned across different metrics/rows. In other words, the values in one column should occupy the same space (append/prepend white space where necessary).

This would help improve readability a little.

Example image below:

![Screen Shot 2019-05-17 at 1 59 22 PM](https://user-images.githubusercontent.com/2479123/57927685-0e894d80-78af-11e9-864d-c36612a169f4.png)

**Comment by na--** [comment] 2021-01-26 14:07
@mpandurovic, can you double-check that this is still an issue? I recently went through the whole summary code because of [`handleSummary()`](https://github.com/loadimpact/k6/blob/master/release%20notes/v0.30.0.md#support-a-handlesummary-callback-at-the-end-of-the-test-1768) and manually transpiled it to JavaScript :sweat_smile: And, from my impressions, the summary should have always been aligned (i.e. space-padded). It hasn't been touched in ~4 years: https://github.com/loadimpact/k6/blame/a948b4dfc0e1be88a3f48206fe04a6fbf18b6301/ui/summary.go#L329-L334

So I assume it's a bug of some sort. And while I found a few in the Go code when transpiling it, I can't think of one that could have caused the issue above, I think... :confused: And I couldn't reproduce it locally...

If you can still reproduce this, can you please also update to k6 v0.30.0 and use the following `handleSummary` function:
```js
import http from 'k6/http';
import k6exmaple from 'https://raw.githubusercontent.com/loadimpact/k6/master/samples/thresholds_readme_example.js';
export default k6exmaple; // use some predefined example to generate some data
export const options = { vus: 5, iterations: 10 };

import { textSummary } from 'https://jslib.k6.io/k6-summary/0.0.1/index.js';

export function handleSummary(data, /*this will be disabled in k6 v0.31.0*/oldGoSummary) {
    var oldSummary = oldGoSummary();
    var newSummary = textSummary(data, { indent: ' ', enableColors: true, });

    return {
        'stdout': 'Old Go summary: \n\n' + oldSummary + '\n\nNew JS summary: \n\n' + newSummary + '\n\n',
        'stdout-old.txt': oldSummary,
        'stdout-new.txt': newSummary,
    }
}
```

And then upload `stdout-old.txt` and `stdout-new.txt` here.

**Comment by na--** [comment] 2021-12-15 12:44
Closing, but will reopen if this is still a bug.

**Closed by na--** 2021-12-15 12:44 UTC
Labels: enhancement, ux, lower prio
