### ISSUE TITLE
k6/http - payload of post method is not correct for nested objects

### ISSUE THREAD

**Issue by alazurenko** [grafana/k6#2369] opened 2022-02-03 15:33 UTC
### Brief summary

Dear Team, 

I'm testing a Service that is accepting the configuration JSON as a POST payload to it to perform a certain operation. 
The payload of the POST method is not properly encoded for the nested object. 

### k6 version

v0.36.0 ((devel), go1.17.6, darwin/amd64)

### OS

masOS 10.15.7

### Steps to reproduce the problem

Create a test 
```js
import http from "k6/http";
import { sleep } from "k6";

export const options = {
  stages: [{ duration: "10s", target: 1 }],
};

const data = {
  id: "id",
  details: {
    url: "http://service.com",
    path: "/api/products",
  },
};

export default function () {
  const res = http.post("my-service.com", data);
  sleep(1);
}
```

### Expected behaviour

The payload to the tested service looks like this:
```js
{
  id: "id",
  details: {
    url: "http://product-service.com",
    path: "/api/products",
  },
}
``` 

### Actual behaviour

The payload on a service looks like this:
```js
{
  details: 'map[path:/api/products url:http://product-service.com]',
  id: 'id',
}
```

**Comment by na--** [comment] 2022-02-03 20:01
This is not really a bug because k6 doesn't serialize JS objects to JSON automatically, it serializes them to `application/x-www-form-urlencoded` or `multipart/form-data`. Only the `map[...]` bit is problematic and likely needs to be changed, though it's not clear it should be into JSON and not something else, e.g. what PHP does for nested objects: `details[path]=/api/products&details[url]=...`. There is no actual standard for encoding nested objects as HTTP body parameters, just different conventions from different programming languages or libraries :man_shrugging: 

https://github.com/grafana/k6/issues/878 is the open issue about automatically marshaling JS objects to JSON request bodies in some cases. However, as explained in the issue comments and some of the linked discussions, it's unlikely we'll do it in the current version of the `k6/http` API because of too much ambiguity. 

For now, you have to manually use [`JSON.stringify()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) for your JSON request bodies, like this:
```js
export default function () {
  const res = http.post("my-service.com", JSON.stringify(data));
  sleep(1);
}
```

I'll close this issue since it's mostly a duplicate of https://github.com/grafana/k6/issues/878, please share any comments you have on this there. This is something we'll try to design better in the next version of the HTTP API, e.g. by having a dedicated REST `Client` that marshals everything to JSON by default or something like that.

**Closed by na--** 2022-02-03 20:01 UTC
Labels: bug

**Comment by alazurenko** [comment] 2022-02-04 10:15
@na-- Thank you for your reply it was helpful! 
Have a nice day!
