### ISSUE TITLE
Log failed requests

### ISSUE THREAD

**Issue by sealr00t** [grafana/k6#2505] opened 2022-04-26 12:28 UTC
### Feature Description

As a k6 user I would like to be able to enable/disable a "switch/flag/option" for logging to console or file only failed http requests, in order for me to easier debug failed http requests. Using `--http-debug="full"` logs all requests and navigating through the logs (for failed ones) is extremely hard. 

### Suggested Solution (optional)

`--http-debug="failed"`

**Comment by MStoykov** [comment] 2022-04-26 12:37
Hi @sealr00t, #2163 already tracks this issue, there is also a comment explaining why this isn't as easy as it might seem. 

Closing this as a duplicate of #2163

**Closed by MStoykov** 2022-04-26 12:37 UTC
Labels: duplicate, feature
