### ISSUE TITLE
`parseHTML()` unsuitable for XML/XHTML with self closing tags: `textContent()` returns next siblings' `textContent`

### ISSUE THREAD

**Issue by gaabora** [grafana/k6#2644] opened 2022-08-12 07:37 UTC
### Brief summary

see steps to reproduce

### k6 version

0.39.0

### OS

Windows 10

### Steps to reproduce the problem

```
import { parseHTML } from 'k6/html'

export const options = {
  executor: 'shared-iterations',
}

export default function () {
  const html = '<!DOCTYPE html><html><body><div data-test="123"/><h1>My Heading</h1><p>My paragraph.</p></body></html>'
  const parsed = parseHTML(html)
  const value = parsed.find('div[data-test]').get(0).getAttribute('data-test')
  const text = parsed.find('div[data-test]').get(0).textContent()
  console.error({ value, text })
}
```

### Expected behaviour

ERRO[0000] {"value":"123","text":""}  source=console

### Actual behaviour

ERRO[0000] {"value":"123","text":"My HeadingMy paragraph."}  source=console

**Comment by na--** [comment] 2022-08-12 07:55
Thanks for opening this issue, though I am not sure this is a bug, exactly :thinking: It seems pretty clear from the code that this is actually the intended behavior:
https://github.com/grafana/k6/blob/5b70e70b657750234651a337c1b736c177926855/js/modules/k6/html/element.go#L222-L224
https://github.com/grafana/k6/blob/5b70e70b657750234651a337c1b736c177926855/vendor/github.com/PuerkitoBio/goquery/property.go#L60-L83

And it seems that it roughly matches the Web API it is attempting to mimic, which also returns the text of the descendants: https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent

So, yeah, this seems like it's working as intended. What is your use case and why is this behavior a problem for you?

**Comment by gaabora** [comment] 2022-08-12 08:03
<body>
  <div data-test="123"/>
  <h1>My Heading</h1>
  <p>My paragraph.</p>
</body>

h1 and p are not descendants of the div, div is self-closed as already mentioned, it does not have any descendants.

**Comment by gaabora** [comment] 2022-08-12 08:13
Weird, so web API wrap them inside... 
Actual use case is parsing xml document with some self-closed tags and getting text content of those tags.

**Comment by gaabora** [comment] 2022-08-12 08:35
Ok, sorry for disturbing, issue should be closed then,
For now, used this workaround to parse xml with self-closing tags with a regular expression, replacing them with normally closed ones:
`''<!DOCTYPE html><html><body><div data-test="123"/><h1>My Heading</h1><p>My paragraph.</p></body></html>''.replace(/<(\w+)([^>]*)\/>/g, '<$1$2></$1>')`

**Comment by na--** [comment] 2022-08-12 09:13
Ah, sorry, I apparently missed the "self closing" part of the title :man_facepalming: :coffee: 

I guess this might also be reason enough to add explicit XML-parsing API in k6 as well :thinking: In the past, we've encouraged people to abuse `parseHTML()` as a quick and dirty alternative for also parsing XML content, which this shows might be a bad idea... :disappointed:

**Comment by na--** [comment] 2022-08-12 09:35
I'll reopen this and adjust the title a bit. 

While k6 might follow browser conventions, I think this is something worth fixing, _probably_ by having a proper XML parsing API. Which also might be needed for other purposes, e.g. https://github.com/grafana/k6/issues/1539. Or, at the very least, we should document this limitation of `parseHTML` when it comes to XHTLM/XML content...

FWIW, `parseHTML()` uses https://github.com/PuerkitoBio/goquery, which in turn uses [`golang.org/x/net/html`](https://github.com/golang/net/tree/master/html), which seems to have a bunch of [`FrozenDueToAge` issues about self-closing tags](https://github.com/golang/go/issues?q=is%3Aissue+%22x%2Fnet%2Fhtml%22+self+closing) :man_facepalming:

**Comment by codebien** [comment] 2024-08-12 16:13
As pointed out in the previous comment, this is a specific limit of the `goquery` library and its engine included in `x/net/html`.

Based on the lack of reactions, we don't plan to address this specific issue in k6. In the future, we might add a better html implementation if there will be the need. Probably, in an extension more than a native module in k6 core.

These days the [browser module](https://grafana.com/docs/k6/latest/using-k6-browser/) exists and it might be an alternative for some of the cases originally covered by the HTML module.

**Closed by codebien** 2024-08-12 16:13 UTC
Labels: bug, docs, evaluation needed
