### ISSUE TITLE
k6 is overwriting URL metric in CSV output when a name tag is specified

### ISSUE THREAD

**Issue by matthewt-assurity** [grafana/k6#3754] opened 2024-05-23 10:31 UTC
### Brief summary

Here are some details about what I'm doing:
- I'm making an HTTP request with `http.get()`
- I'm specifying a `name` tag for the HTTP request.
- I'm writing results to a CSV output file with `--out "csv=logs/test_results.csv"` as a command line argument.

My problem is: when I look at the test results, I see that the URL of the HTTP request has been overridden by the `name` tag value. For example: if I set the `name` tag to be "home page request", the CSV output will contain "home page request" in both the URL and name columns.

Based on my understanding of the k6 docs, this is not how using the `name` tag should work. It should overwrite the name field only, not the URL field https://grafana.com/docs/k6/latest/using-k6/http-requests/#url-grouping

### k6 version

v0.51.0

### OS

Windows 11

### Steps to reproduce the problem

Make an http request in a k6 script, e.g

```javascript
export default function () {
    const res = http.get("https://www.google.com/", {
        tags: {
            name: "home page request"
        }
    });
}
```

And run k6 with the below
```bash
k6 script.js --out "csv=logs/test_results.csv"
```

### Expected behaviour

The URL column in the CSV file should be "https://www.google.com/"

### Actual behaviour

The URL column in the CSV file is "home page request"

**Comment by olegbespalov** [comment] 2024-05-23 10:37
Hi @matthewt-assurity !

It's not the bug of the CSV output but an expected behavior of the HTTP module after the https://github.com/grafana/k6/pull/2703

I belive we [should document this better](https://github.com/grafana/k6-docs/issues/1481#issuecomment-1895560120) (including the rationale) 

cc: @codebien

**Comment by matthewt-assurity** [comment] 2024-05-23 10:46
Thanks for the quick reply @olegbespalov 

I'll have to read those tickets to understand the rationale better, but good to hear it is expected behaviour and not a bug. 

I agree, this should absolutely be documented better, as the documentation I read is out of date. 

To clarify my exact use-case better: I want to be able to tag requests that have been made together as part of a transaction. Perhaps I should be using groups? Or adding my own custom tag? Or another recommended approach?

**Comment by matthewt-assurity** [comment] 2024-05-23 10:50
Also out of curiosity, is the documentation on this page out of date? https://grafana.com/docs/k6/latest/using-k6/tags-and-groups/#tags-in-results-output

The JSON output example does not include a `name` tag, just `url`. Perhaps this is correct functionality based on the links you've posted (it sounds like url and name are effectively the same field now, so we don't need both? But I don't think thats correct since my output is still logging both the url and name fields :) )

**Comment by olegbespalov** [comment] 2024-05-23 14:35
> To clarify my exact use-case better: I want to be able to tag requests that have been made together as part of a transaction. Perhaps I should be using groups? Or adding my own custom tag? Or another recommended approach?

Yes, for that need, both options are the way to go. Depending on the actual structure of your requests you could pick the right one. 

>The JSON output example does not include a name tag, just url. Perhaps this is correct functionality based on the links you've posted (it sounds like url and name are effectively the same field now, so we don't need both? But I don't think thats correct since my output is still logging both the url and name fields :) )

I believe it's again a bit outdated example :cry: I mean, I've just tried to run the JSON output, and it produces JSON like:
```
{
   "metric": "http_reqs",
   "type": "Point",
   "data": {
      "time": "2024-05-23T16:29:20.78124455+02:00",
      "value": 1,
      "tags": {
         "containerGroup": "main",
         "expected_response": "true",
         "group": "::main",
         "method": "GET",
         "name": "https://test.k6.io",
         "proto": "HTTP/1.1",
         "scenario": "default",
         "status": "200",
         "tls_version": "tls1.3",
         "url": "https://test.k6.io"
      }
   }
}
```

**Comment by olegbespalov** [comment] 2024-06-04 12:27
I am closing this as it's not a bug, and we have other issues with fixing the docs.

**Closed by olegbespalov** 2024-06-04 12:27 UTC
Labels: triage
